#!/usr/bin/env ruby
#This is free and unencumbered software released into the public domain.

#Anyone is free to copy, modify, publish, use, compile, sell, or
#distribute this software, either in source code form or as a compiled
#binary, for any purpose, commercial or non-commercial, and by any
#means.

#In jurisdictions that recognize copyright laws, the author or authors
#of this software dedicate any and all copyright interest in the
#software to the public domain. We make this dedication for the benefit
#of the public at large and to the detriment of our heirs and
#successors. We intend this dedication to be an overt act of
#relinquishment in perpetuity of all present and future rights to this
#software under copyright law.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
#OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
#ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
#OTHER DEALINGS IN THE SOFTWARE.

#For more information, please refer to <http://unlicense.org>

if ARGV.length < 2
	puts "usage: precomp num inputbyte1 ..."
	exit -1
end

cmd = "go run"
spacer = ""

if $0 !~ /run/
 cmd = "dlv debug"
 spacer = "--"
end

input = ARGV[1..-1].map { |c| sprintf "%02x", c.to_i }.join
inputsize = ARGV.length - 1
immediatesize = inputsize.size / 8
code ="#{sprintf "%02x", (0x60 - immediatesize + 1)}#{sprintf "%0#{2*immediatesize}x", inputsize}60006000376000600160#{sprintf "%0#{2*immediatesize}x", inputsize}600060ff60046006f100"

puts code
puts ARGV.length

#system "go run ./cmd/evm/ --input #{code} disasm"
system "#{cmd} ./cmd/evm/ #{spacer} --code=#{code} --prestate my_genesis.json --receiver a8c3eeb2915373139bcfc287d4ae9e660d734881 --input #{input} -json run"
